swipe:
  3:
    left:
      command: 'xdotool key ctrl+shift+Tab'
      threshold: 0.05
    right:
      command: 'xdotool key ctrl+Tab'
      threshold: 0.05
    up:
      command: 'xdotool key super+Left'
    down:
      command: 'xdotool key super+Right'
  4:
    left:
      command: "xdotool key ctrl+super+Left"
      threshold: 0.05
    right:
      command: "xdotool key ctrl+super+Right"
      threshold: 0.05
    up:
      command: 'xdotool key alt+Left'
    down:
      command: "xdotool key alt+Right"
pinch:
  2:
    in:
      command: 'xdotool key ctrl+plus'
    out:
      command: 'xdotool key ctrl+minus'

threshold:
  swipe: 0.2
  pinch: 0.2
